package com.bdqn.auction.settings.entity;

import org.apache.ibatis.type.Alias;

@Alias("auctionUser")
public class AuctionUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_auction_user.user_id
     *
     * @mbggenerated Sat Sep 17 14:08:37 CST 2022
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_auction_user.user_name
     *
     * @mbggenerated Sat Sep 17 14:08:37 CST 2022
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_auction_user.user_pwd
     *
     * @mbggenerated Sat Sep 17 14:08:37 CST 2022
     */
    private String userPwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_auction_user.user_card_no
     *
     * @mbggenerated Sat Sep 17 14:08:37 CST 2022
     */
    private String userCardNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_auction_user.user_tel
     *
     * @mbggenerated Sat Sep 17 14:08:37 CST 2022
     */
    private String userTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_auction_user.user_address
     *
     * @mbggenerated Sat Sep 17 14:08:37 CST 2022
     */
    private String userAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_auction_user.user_post_number
     *
     * @mbggenerated Sat Sep 17 14:08:37 CST 2022
     */
    private String userPostNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_auction_user.user_ls_admin
     *
     * @mbggenerated Sat Sep 17 14:08:37 CST 2022
     */
    private String userLsAdmin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_auction_user.user_question
     *
     * @mbggenerated Sat Sep 17 14:08:37 CST 2022
     */
    private String userQuestion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_auction_user.user_answer
     *
     * @mbggenerated Sat Sep 17 14:08:37 CST 2022
     */
    private String userAnswer;

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_auction_user.user_name
     *
     * @return the value of t_auction_user.user_name
     * @mbggenerated Sat Sep 17 14:08:37 CST 2022
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_auction_user.user_name
     *
     * @param userName the value for t_auction_user.user_name
     * @mbggenerated Sat Sep 17 14:08:37 CST 2022
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_auction_user.user_pwd
     *
     * @return the value of t_auction_user.user_pwd
     * @mbggenerated Sat Sep 17 14:08:37 CST 2022
     */
    public String getUserPwd() {
        return userPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_auction_user.user_pwd
     *
     * @param userPwd the value for t_auction_user.user_pwd
     * @mbggenerated Sat Sep 17 14:08:37 CST 2022
     */
    public void setUserPwd(String userPwd) {
        this.userPwd = userPwd == null ? null : userPwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_auction_user.user_card_no
     *
     * @return the value of t_auction_user.user_card_no
     * @mbggenerated Sat Sep 17 14:08:37 CST 2022
     */
    public String getUserCardNo() {
        return userCardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_auction_user.user_card_no
     *
     * @param userCardNo the value for t_auction_user.user_card_no
     * @mbggenerated Sat Sep 17 14:08:37 CST 2022
     */
    public void setUserCardNo(String userCardNo) {
        this.userCardNo = userCardNo == null ? null : userCardNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_auction_user.user_tel
     *
     * @return the value of t_auction_user.user_tel
     * @mbggenerated Sat Sep 17 14:08:37 CST 2022
     */
    public String getUserTel() {
        return userTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_auction_user.user_tel
     *
     * @param userTel the value for t_auction_user.user_tel
     * @mbggenerated Sat Sep 17 14:08:37 CST 2022
     */
    public void setUserTel(String userTel) {
        this.userTel = userTel == null ? null : userTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_auction_user.user_address
     *
     * @return the value of t_auction_user.user_address
     * @mbggenerated Sat Sep 17 14:08:37 CST 2022
     */
    public String getUserAddress() {
        return userAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_auction_user.user_address
     *
     * @param userAddress the value for t_auction_user.user_address
     * @mbggenerated Sat Sep 17 14:08:37 CST 2022
     */
    public void setUserAddress(String userAddress) {
        this.userAddress = userAddress == null ? null : userAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_auction_user.user_post_number
     *
     * @return the value of t_auction_user.user_post_number
     * @mbggenerated Sat Sep 17 14:08:37 CST 2022
     */
    public String getUserPostNumber() {
        return userPostNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_auction_user.user_post_number
     *
     * @param userPostNumber the value for t_auction_user.user_post_number
     * @mbggenerated Sat Sep 17 14:08:37 CST 2022
     */
    public void setUserPostNumber(String userPostNumber) {
        this.userPostNumber = userPostNumber == null ? null : userPostNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_auction_user.user_ls_admin
     *
     * @return the value of t_auction_user.user_ls_admin
     * @mbggenerated Sat Sep 17 14:08:37 CST 2022
     */
    public String getUserLsAdmin() {
        return userLsAdmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_auction_user.user_ls_admin
     *
     * @param userLsAdmin the value for t_auction_user.user_ls_admin
     * @mbggenerated Sat Sep 17 14:08:37 CST 2022
     */
    public void setUserLsAdmin(String userLsAdmin) {
        this.userLsAdmin = userLsAdmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_auction_user.user_question
     *
     * @return the value of t_auction_user.user_question
     * @mbggenerated Sat Sep 17 14:08:37 CST 2022
     */
    public String getUserQuestion() {
        return userQuestion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_auction_user.user_question
     *
     * @param userQuestion the value for t_auction_user.user_question
     * @mbggenerated Sat Sep 17 14:08:37 CST 2022
     */
    public void setUserQuestion(String userQuestion) {
        this.userQuestion = userQuestion == null ? null : userQuestion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_auction_user.user_answer
     *
     * @return the value of t_auction_user.user_answer
     * @mbggenerated Sat Sep 17 14:08:37 CST 2022
     */
    public String getUserAnswer() {
        return userAnswer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_auction_user.user_answer
     *
     * @param userAnswer the value for t_auction_user.user_answer
     * @mbggenerated Sat Sep 17 14:08:37 CST 2022
     */
    public void setUserAnswer(String userAnswer) {
        this.userAnswer = userAnswer == null ? null : userAnswer.trim();
    }

    @Override
    public String toString() {
        return "AuctionUser{" +
                "userId=" + userId +
                ", userName='" + userName + '\'' +
                ", userPwd='" + userPwd + '\'' +
                ", userCardNo='" + userCardNo + '\'' +
                ", userTel='" + userTel + '\'' +
                ", userAddress='" + userAddress + '\'' +
                ", userPostNumber='" + userPostNumber + '\'' +
                ", userLsAdmin=" + userLsAdmin +
                ", userQuestion='" + userQuestion + '\'' +
                ", userAnswer='" + userAnswer + '\'' +
                '}';
    }
}