package com.bdqn.auction.settings.mapper;

import com.bdqn.auction.settings.entity.AuctionUser;

import java.util.List;
import java.util.Map;

public interface AuctionUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_auction_user
     *
     * @mbggenerated Sat Sep 17 14:08:37 CST 2022
     */
    int deleteByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_auction_user
     *
     * @mbggenerated Sat Sep 17 14:08:37 CST 2022
     */
    int insert(AuctionUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_auction_user
     *
     * @mbggenerated Sat Sep 17 14:08:37 CST 2022
     */
    int insertSelective(AuctionUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_auction_user
     *
     * @mbggenerated Sat Sep 17 14:08:37 CST 2022
     */
    AuctionUser selectByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_auction_user
     *
     * @mbggenerated Sat Sep 17 14:08:37 CST 2022
     */
    int updateByPrimaryKeySelective(AuctionUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_auction_user
     *
     * @mbggenerated Sat Sep 17 14:08:37 CST 2022
     */
    int updateByPrimaryKey(AuctionUser record);

    /**
     * 插入普通用户
     */
    int insertActionUser(AuctionUser auctionUser);

    /**
     * 根据用户名和密码查询用户
     */
    AuctionUser selectAuctionUserByUserNameAndPwd(Map<String, String> map);

    /**
     * 根据id查询多条用户
     */
    List<AuctionUser> selectAuctionListUserById(String auctionUserId);
    /**
     * 根据id查询用户
     */
    AuctionUser selectAuctionUserByAuctionUserId(String auctionUserId);
}